# Generated by Django 3.2.4 on 2021-06-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0006_auto_20210613_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='isseller',
        ),
        migrations.AddField(
            model_name='users',
            name='roles',
            field=models.CharField(blank=True, max_length=10, verbose_name='权限'),
        ),
    ]
