# Generated by Django 3.2.4 on 2021-06-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0007_auto_20210614_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='signature',
            field=models.CharField(blank=True, max_length=300, verbose_name='个性签名'),
        ),
    ]
