# Generated by Django 3.2.4 on 2021-06-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0009_goods_imgsrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_rank', models.IntegerField(default=0, verbose_name='VIP等级')),
                ('vip_exp', models.IntegerField(default=0, verbose_name='VIP当前经验')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appstore.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_No', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('order_status', models.CharField(default='未支付', max_length=20, verbose_name='订单状态')),
                ('order_created_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('order_paid_time', models.DateTimeField(blank=True, verbose_name='订单支付时间')),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appstore.goods')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appstore.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_created_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appstore.goods')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appstore.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_created_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appstore.goods')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appstore.users')),
            ],
        ),
    ]
