# Generated by Django 3.2.4 on 2021-06-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0010_userchart_userfavorites_userorders_uservip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchart',
            name='chart_created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='加入购物车时间'),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='fav_created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='收藏时间'),
        ),
    ]
