# Generated by Django 3.2.4 on 2021-06-16 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0012_auto_20210615_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='imgSrc',
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_info',
            field=models.CharField(blank=True, max_length=1000, verbose_name='商品描述'),
        ),
        migrations.CreateModel(
            name='goodsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgSrc', models.CharField(default='', max_length=100, verbose_name='商品照片')),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appstore.goods')),
            ],
        ),
    ]
