# Generated by Django 3.2.4 on 2021-06-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0013_auto_20210616_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimg',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstore.goods'),
        ),
        migrations.CreateModel(
            name='GoodsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgSrc', models.CharField(default='', max_length=30, verbose_name='商品标签')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstore.goods')),
            ],
        ),
    ]
