# Generated by Django 3.2.4 on 2021-06-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0015_rename_imgsrc_goodstags_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstags',
            name='tags',
            field=models.CharField(default='', max_length=30),
        ),
    ]
