# Generated by Django 3.2.4 on 2021-06-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0019_alter_goodshisdata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='highest_price',
            field=models.IntegerField(default=0, verbose_name='最高价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(default=0, verbose_name='初始价格'),
        ),
    ]
