# Generated by Django 3.2.4 on 2021-06-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0021_userorders_order_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorders',
            old_name='order_place',
            new_name='order_address',
        ),
    ]
