# Generated by Django 3.2.4 on 2021-06-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0022_rename_order_place_userorders_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorders',
            name='price',
            field=models.IntegerField(default=0, verbose_name='订单价格'),
        ),
    ]
