# Generated by Django 3.2.4 on 2021-06-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0023_userorders_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorders',
            name='order_created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='订单创建时间'),
        ),
    ]
