# Generated by Django 3.2.4 on 2021-06-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0024_alter_userorders_order_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorders',
            name='order_paid_time',
            field=models.CharField(blank=True, max_length=30, verbose_name='订单支付时间'),
        ),
    ]
