# Generated by Django 3.2.4 on 2021-06-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0025_alter_userorders_order_paid_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
    ]
