# Generated by Django 3.2.4 on 2021-06-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0026_alter_goods_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_tags',
            field=models.CharField(blank=True, max_length=100, verbose_name='商品标签'),
        ),
        migrations.DeleteModel(
            name='GoodsTags',
        ),
    ]
