# Generated by Django 3.2.4 on 2021-06-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0027_auto_20210620_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_tags',
            field=models.CharField(default='其他', max_length=100, verbose_name='商品标签'),
        ),
    ]
